In [1]:
#John David Conley
#Deep Learning assignment 3

#1. Implement Naïve Bayes method using scikit-learn library
#Use dataset available with name glass
#Use train_test_split to create training and testing part
#Evaluate the model on test part using score and classification_report(y_true, y_pred)

#2. Implement linear SVM method using scikit library
#Use the same dataset above
#Use train_test_split to create training and testing part
#Evaluate the model on test part using score and classification_report(y_true, y_pred)
#Which algorithm you got better accuracy? Can you justify why

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression, RidgeClassifierCV, Perceptron, SGDClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, accuracy_score
from sklearn.model_selection import cross_val_score, GridSearchCV, train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import normalize
from sklearn.svm import SVC, LinearSVC
from sklearn.tree import DecisionTreeClassifier

import warnings
warnings.filterwarnings("ignore")

In [2]:
#1
glass = pd.read_csv('glass.csv')
iris = pd.read_csv('Iris.csv')
combine = [glass, iris]

glassNorm=normalize(glass)

display("Glass", glass)
print("Normalized\n", glassNorm)
#print("Iris\n", iris)
#print("Combine\n", combine)

'Glass'

          RI     Na    Mg    Al     Si     K    Ca    Ba   Fe  Type
0    1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0     1
1    1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0     1
2    1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0     1
3    1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0     1
4    1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0     1
..       ...    ...   ...   ...    ...   ...   ...   ...  ...   ...
209  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0     7
210  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0     7
211  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0     7
212  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.0     7
213  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.0     7

[214 rows x 10 columns]

Normalized
 [[0.02062272 0.18493886 0.06087797 ... 0.         0.         0.01355857]
 [0.02034864 0.18624195 0.04827005 ... 0.         0.         0.01340835]
 [0.02027973 0.18097109 0.04748318 ... 0.         0.         0.01337554]
 ...
 [0.02009568 0.18977016 0.         ... 0.02167292 0.         0.09250635]
 [0.01999105 0.18956111 0.         ... 0.02069617 0.         0.09227592]
 [0.02006488 0.1882021  0.         ... 0.02208696 0.         0.09258009]]

In [3]:
print("Glass\n", glass.describe())
#print("Iris\n", iris.describe())
#print("Combine\n", iris.describe())

Glass
                RI          Na          Mg          Al          Si           K  \
count  214.000000  214.000000  214.000000  214.000000  214.000000  214.000000
mean     1.518365   13.407850    2.684533    1.444907   72.650935    0.497056
std      0.003037    0.816604    1.442408    0.499270    0.774546    0.652192
min      1.511150   10.730000    0.000000    0.290000   69.810000    0.000000
25%      1.516522   12.907500    2.115000    1.190000   72.280000    0.122500
50%      1.517680   13.300000    3.480000    1.360000   72.790000    0.555000
75%      1.519157   13.825000    3.600000    1.630000   73.087500    0.610000
max      1.533930   17.380000    4.490000    3.500000   75.410000    6.210000

               Ca          Ba          Fe        Type
count  214.000000  214.000000  214.000000  214.000000
mean     8.956963    0.175047    0.057009    2.780374
std      1.423153    0.497219    0.097439    2.103739
min      5.430000    0.000000    0.000000    1.000000
25%      8.240000    0.000000    0.000000    1.000000
50%      8.600000    0.000000    0.000000    2.000000
75%      9.172500    0.000000    0.100000    3.000000
max     16.190000    3.150000    0.510000    7.000000

In [4]:
#Normalizing didn't work
#glass2 = glass.copy()
#for column in glass2.columns:
#    glass2[column] = (glass2[column] - glass2[column].min()) / (glass2[column].max() - glass2[column].min())  
#display(glass2)
    
glasX = glass.values[:, 0:-1]
glasY = glass.values[:, -1]

glasX_train, glasX_test, glasY_train, glasY_test = train_test_split(glasX, glasY, test_size = 0.2, random_state = 0)

#glasX_train=normalize(glasX_train)
#glasX_test=normalize(glasX_test)
#glasY_train=normalize(glasY_train)
#glasY_test=normalize(glasY_test)

In [5]:
glasclassifierGNB = GaussianNB()
glasclassifierGNB.fit(glasX_train, glasY_train)

glasY_predGNB = glasclassifierGNB.predict(glasX_test)

print(classification_report(glasY_test, glasY_predGNB))
print(confusion_matrix(glasY_test, glasY_predGNB))
print('accuracy is',accuracy_score(glasY_predGNB,glasY_test))

              precision    recall  f1-score   support

         1.0       0.19      0.44      0.27         9
         2.0       0.33      0.16      0.21        19
         3.0       0.33      0.20      0.25         5
         5.0       0.00      0.00      0.00         2
         6.0       0.67      1.00      0.80         2
         7.0       1.00      1.00      1.00         6

    accuracy                           0.37        43
   macro avg       0.42      0.47      0.42        43
weighted avg       0.40      0.37      0.36        43

[[ 4  3  1  0  1  0]
 [14  3  1  1  0  0]
 [ 3  1  1  0  0  0]
 [ 0  2  0  0  0  0]
 [ 0  0  0  0  2  0]
 [ 0  0  0  0  0  6]]
accuracy is 0.37209302325581395

In [6]:
#2
glasclassifierSVC = SVC()
glasclassifierSVC.fit(glasX_train, glasY_train)

glasY_predSVC = glasclassifierSVC.predict(glasX_test)

print(classification_report(glasY_test, glasY_predSVC))
print(confusion_matrix(glasY_test, glasY_predSVC))
print('accuracy is',accuracy_score(glasY_predSVC,glasY_test))

              precision    recall  f1-score   support

         1.0       0.21      1.00      0.35         9
         2.0       0.00      0.00      0.00        19
         3.0       0.00      0.00      0.00         5
         5.0       0.00      0.00      0.00         2
         6.0       0.00      0.00      0.00         2
         7.0       0.00      0.00      0.00         6

    accuracy                           0.21        43
   macro avg       0.03      0.17      0.06        43
weighted avg       0.04      0.21      0.07        43

[[ 9  0  0  0  0  0]
 [19  0  0  0  0  0]
 [ 5  0  0  0  0  0]
 [ 2  0  0  0  0  0]
 [ 2  0  0  0  0  0]
 [ 6  0  0  0  0  0]]
accuracy is 0.20930232558139536

In [ ]:
print('Bayes is giving me higher accuracy score due to how it manipulates the data compared to SVC. SVC is giving me a large amount of zeroes regardless of how I tweak it - and normalization did not work - likely owing as well to the large amount of zeroes in the source data.')